[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
soltip = "HGT4DoDJ1crx3HM28t1CJBT2KAAzK44y3esrNWCtP1JE"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "bash -lc 'source \"$HOME/.cargo/env\" 2>/dev/null || true; cargo test -p soltip'"

[hooks]
