[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
soltip = "HGT4DoDJ1crx3HM28t1CJBT2KAAzK44y3esrNWCtP1JE"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
